[general]
debug = true
timezone = "Asia/Yerevan"
base_packages = "base base-devel linux linux-firmware iwd dhcpcd git"

[user]
username = "vgevorgyan"
home = "/home/vgevorgyan"

[network]
type = "eth"
hostname = "vgevorgyan"

[network.eth]
type = "dhcp"

[disks]
action = "mount"

[[disks.partitions]]
name = "system"
type = "luks-lvm2"
password = "TestTest"
partition = "/dev/vda4"
crypt_name = "cryptlvm"

[[disks.system.partitions]]
mount = "/"
name = "root"
format = true

[[disks.system.partitions]]
mount = "/home"
name = "home"
format = false

[[disks.system.partitions]]
mount = "/home/data"
name = "data"
format = false

[[disks.partitions]]
type = "boot"
partition = "/dev/vda2"
format = true

[[disks.partitions]]
type = "efi"
partition = "/dev/vda1"
format = true

[[disks.partitions]]
type = "swap"
partition = "/dev/vda3"
format = true
